export {
  generatePath,
  Link,
  matchPath,
  NavLink,
  Prompt,
  Redirect,
  Route,
  Router,
  Switch,
  useHistory,
  useLocation,
  useParams,
  useRouteMatch,
  withRouter,
} from 'react-router-dom';
export type {
  LinkProps,
  match,
  NavLinkProps,
  PromptProps,
  RedirectProps,
  RouteChildrenProps,
  RouteComponentProps,
  RouteProps,
  RouterChildContext,
  RouterProps,
  SwitchProps,
} from 'react-router-dom';
